name: NuGet Package Publish

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'

    - name: Extract version from csproj
      id: extract-version
      run: |
        version=$(grep "<Version>" MihomoSharp.csproj | sed -e 's/<Version>//g' -e 's/<\/Version>//g')
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Pack
      run: dotnet pack --no-build --configuration Release

    - name: Debug output
      run: |
        echo "Pushing package: bin/Release/MihomoSharp.${{ env.VERSION }}.nupkg"

    - name: Publish
      run: |
        dotnet nuget push "bin/Release/MihomoSharp.${{ env.VERSION }}.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}