name: NuGet Package Publish

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'


    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Pack
      id: pack
      run: |
        dotnet pack --no-build --configuration Release
        echo "PACKAGE_PATH=$(ls bin/Release/*.nupkg)" >> $GITHUB_ENV

    - name: Publish
      run: |
        dotnet nuget push ${{ env.PACKAGE_PATH }} -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}